# Generated by Django 5.0.6 on 2024-06-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='full_name',
            new_name='name',
        ),
    ]
