# Generated by Django 5.0.6 on 2024-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_full_name_userinformation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='date_of_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
